// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:insight/models/attendance.dart';
import 'package:insight/models/student.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceAdapter());
    registerAdapter(StudentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceAdapter());
    registerAdapter(StudentAdapter());
  }
}
